[build]
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "/.netlify/functions/robots"
  status = 200

[[redirects]]
  from = "/articles/:id"
  to = "/.netlify/functions/article-meta/:id"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://.googletagmanager.com https://.google-analytics.com https://pagead2.googlesyndication.com https://partner.googleadservices.com https://tpc.googlesyndication.com https://www.googletagservices.com; style-src 'self' 'unsafe-inline'; img-src * blob: data:; font-src 'self' data:; connect-src 'self' https://kxeqswkkvjvedhxlzxph.supabase.co https://.google-analytics.com https://.googletagmanager.com https://pagead2.googlesyndication.com https://googleads.g.doubleclick.net https://tpc.googlesyndication.com; frame-src https://www.youtube.com https://youtube.com https://www.googletagmanager.com https://googleads.g.doubleclick.net https://pagead2.googlesyndication.com"