[build]
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "/.netlify/functions/robots"
  status = 200
