backend:
  name: git-gateway
  branch: main   # or "master", depending on your repo default branch

media_folder: "public/uploads"    # where images will be stored
public_folder: "/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "src/content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "body", label: "Body", widget: "markdown" }
